name: Publish site

on:
  push:
    branches:
      - source

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v3
        with:
          ref: source
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential g++ python3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Change to yarn v4
        run: |
          npm install -g npm
          npm uninstall -g  yarn pnpm
          npm install -g corepack
          corepack enable
          corepack install --global yarn
      - name: Install dependencies
        run: |
          yarn up
          yarn install --inline-builds
      - name: Build site
        run: |
          export PATH=$PATH./node_modules/.bin
          hexo clean
          hexo generate
      - name: Deploy to GitHub Pages
        run: hexo deploy
